spring:    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
        filters:
        - AuthenticationFilter
        
       
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
          - Path=/ratings/**
        filters:
        - AuthenticationFilter
          
      - id: HOTAL-SERVICE
        uri: lb://HOTAL-SERVICE
        predicates:
          - Path=/hotals/**,/staffs/**
          
    
server:
  port: 8084
 
 
eureka:
 instance:
    prefer-ip-address: true
 client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8080/eureka
      
      
